### ISSUE TITLE
ValueError: Only layers of same output shape can be merged using sum mode

### ISSUE THREAD

**Issue by bingo619** [lucktroy/DeepST#1]
Both Windows and Mac OS. All latest libraries.

**Comment by lucktroy** [comment]
@bingo619 would you print the full errors? thx.

**Comment by bingo619** [comment]
/usr/bin/python /Users/xxx/DeepST/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py
Using Theano backend.
factor:  1.25707872211
loading data...
('incomplete days: ', [])
train_data shape:  (4152, 2, 16, 8)
min: 0.0 max: 267.0
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
train shape: (3480, 6, 16, 8) (3480, 2, 16, 8) test shape:  (240, 6, 16, 8) (240, 2, 16, 8)
(3480, 6, 16, 8)
(3480, 8, 16, 8)
(3480, 8, 16, 8)
(3480, 8)

(240, 6, 16, 8)
(240, 8, 16, 8)
(240, 8, 16, 8)
(240, 8)


 days (test):  ['20140921', '20140922', '20140923', '20140924', '20140925', '20140926', '20140927', '20140928', '20140929', '20140930']
==========
compiling model...
**at the first time, it takes a few minites to compile if you use [Theano] as the backend**
Traceback (most recent call last):
  File "/Users/hongbinliu/DeepST/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 149, in <module>
    main()
  File "/Users/hongbinliu/DeepST/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 87, in main
    model = build_model(external_dim)
  File "/Users/hongbinliu/DeepST/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 65, in build_model
    external_dim=external_dim, nb_residual_unit=nb_residual_unit)
  File "/Users/hongbinliu/DeepST/deepst/models/STResNet.py", line 87, in stresnet
    main_output = merge(new_outputs, mode='sum')
  File "/Library/Python/2.7/site-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py", line 1674, in merge
    name=name)
  File "/Library/Python/2.7/site-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py", line 1293, in __init__
    node_indices, tensor_indices)
  File "/Library/Python/2.7/site-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py", line 1329, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 16, 2), (None, 8, 16, 2), (None, 8, 16, 2)]

Process finished with exit code 1

**Comment by bingo619** [comment]
And I am using Keras version 1.2.0, thanks a lot.

**Comment by lucktroy** [comment]
This issue is caused by the latest default configuration of Keras. *image_dim_ordering* in ~/.keras/keras.json should be *th*. 

You can find the complete configuration as follows. Thanks. 

# configuration file of Keras: ~/.keras/keras.json
{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}

**Comment by bingo619** [comment]
Thanks Junbo, works like a charm.

**Comment by lucktroy** [comment]
@bingo619 I also have updated [ReadMe.md](https://github.com/lucktroy/DeepST/blob/master/README.md). Thanks for submitting this issue. O(∩_∩)O~

**Comment by wangbao** [comment]
Hi, I am really interested in this project. I tried to run this code on Ubuntu 16.04, however, I got exactly the same error as bingo619 reported. I changed the configuration file of Keras as above, the error in layer merge remains unsolved. Would you mind to give some tips? The keras configuration file is:
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}

**Comment by wangbao** [comment]
The following is the error reported: 

Using Theano backend.
factor:  1.25707872211
loading data...
('incomplete days: ', [])
train_data shape:  (4152, 2, 16, 8)
min: 0.0 max: 267.0
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
train shape: (3480, 6, 16, 8) (3480, 2, 16, 8) test shape:  (240, 6, 16, 8) (240, 2, 16, 8)
(3480, 6, 16, 8)
(3480, 8, 16, 8)
(3480, 8, 16, 8)
(3480, 8)

(240, 6, 16, 8)
(240, 8, 16, 8)
(240, 8, 16, 8)
(240, 8)


 days (test):  ['20140921', '20140922', '20140923', '20140924', '20140925', '20140926', '20140927', '20140928', '20140929', '20140930']
==========
compiling model...
**at the first time, it takes a few minites to compile if you use [Theano] as the backend**
/home/baowang/Desktop/DeepLearningSpatioTemporal/DeepST/deepst/models/STResNet.py:69: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(padding="same", filters=64, kernel_size=(3, 3))`
  nb_filter=64, nb_row=3, nb_col=3, border_mode="same")(input)
/home/baowang/Desktop/DeepLearningSpatioTemporal/DeepST/deepst/models/STResNet.py:28: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(padding="same", strides=(1, 1), filters=64, kernel_size=(3, 3))`
  return Convolution2D(nb_filter=nb_filter, nb_row=nb_row, nb_col=nb_col, subsample=subsample, border_mode="same")(activation)
/home/baowang/Desktop/DeepLearningSpatioTemporal/DeepST/deepst/models/STResNet.py:20: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return merge([input, residual], mode='sum')
/home/baowang/anaconda/lib/python2.7/site-packages/keras/legacy/layers.py:456: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
/home/baowang/Desktop/DeepLearningSpatioTemporal/DeepST/deepst/models/STResNet.py:76: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(padding="same", filters=2, kernel_size=(3, 3))`
  nb_filter=nb_flow, nb_row=3, nb_col=3, border_mode="same")(activation)
/home/baowang/anaconda/lib/python2.7/site-packages/keras/engine/topology.py:561: UserWarning: Class `deepst.models.iLayer.iLayer` defines `get_output_shape_for` but does not override `compute_output_shape`. If this is a Keras 1 layer, please implement `compute_output_shape` to support Keras 2.
  output_shape = self.compute_output_shape(input_shape)
/home/baowang/Desktop/DeepLearningSpatioTemporal/DeepST/deepst/models/STResNet.py:87: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  main_output = merge(new_outputs, mode='sum')
Traceback (most recent call last):
  File "exptBikeNYC.py", line 149, in <module>
    main()
  File "exptBikeNYC.py", line 87, in main
    model = build_model(external_dim)
  File "exptBikeNYC.py", line 65, in build_model
    external_dim=external_dim, nb_residual_unit=nb_residual_unit)
  File "/home/baowang/Desktop/DeepLearningSpatioTemporal/DeepST/deepst/models/STResNet.py", line 87, in stresnet
    main_output = merge(new_outputs, mode='sum')
  File "/home/baowang/anaconda/lib/python2.7/site-packages/keras/legacy/layers.py", line 456, in merge
    name=name)
  File "/home/baowang/anaconda/lib/python2.7/site-packages/keras/legacy/layers.py", line 107, in __init__
    node_indices, tensor_indices)
  File "/home/baowang/anaconda/lib/python2.7/site-packages/keras/legacy/layers.py", line 151, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 16, 2), (None, 8, 16, 2), (None, 8, 16, 2)]

**Comment by ZhangJing1048** [comment]
I also met the same problem,and the full information is:
Traceback (most recent call last):
  File "D:/DeepST/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 149, in <module>
    main()
  File "D:/DeepST/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 87, in main
    model = build_model(external_dim)
  File "D:/DeepST/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 65, in build_model
    external_dim=external_dim, nb_residual_unit=nb_residual_unit)
  File "d:\deepst\deepst\models\STResNet.py", line 91, in stresnet
    main_output = merge(new_outputs, mode='sum')
  File "D:\Anaconda\lib\site-packages\keras\legacy\layers.py", line 467, in merge
    name=name)
  File "D:\Anaconda\lib\site-packages\keras\legacy\layers.py", line 107, in __init__
    node_indices, tensor_indices)
  File "D:\Anaconda\lib\site-packages\keras\legacy\layers.py", line 152, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 16, 2), (None, 8, 16, 2), (None, 8, 16, 2)]

Process finished with exit code 1
do you know how to solve it?

**Comment by ZhangJing1048** [comment]
and I have change the configuration file keras.json like you wrote above,could you help me with the problem?

**Comment by vincent-inspectionapps** [comment]
@ZhangJing1048 In the lastest Keras, the config has been changed, you can either use older version, or change the config accordingly.

{
    "image_data_format": "channels_last",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}
reference: [](https://keras.io/backend/)

**Comment by lucktroy** [comment]
@ZhangJing1048 Thanks! In Keras 2.0, the config has changed!

**Comment by ZhangJing1048** [comment]
@vincent-inspectionapps @lucktroy so you mean that I should use keras1 and an  olser version thano, or use tensorflow and keras2(my current keras version)?

**Comment by vincent-inspectionapps** [comment]
Well, I think either should be fine, just to make sure you got the config right.

Personally I used tensorflow and both keras 1.2 and 2.*, all worked great.

**Comment by vincent-inspectionapps** [comment]
Just to clarify the config above is just an example I copied from the website.

It actually should always be channels_last which is the Theano style image dim.

**Comment by lucktroy** [comment]
@ZhangJing1048 At present, I only ran on Keras 1.2. From the response of @vincent-inspectionapps , it seems to work well using Keras 2.0 with new config. Thanks Vincent.

**Comment by ZhangJing1048** [comment]
Thank you so much,I have solve this problem by using Kreas 1.2.0,and it work well.Thank you @Junbo@vincent

**Comment by shaomai00** [comment]
@vincent-inspectionapps I met this problem and my keras version is 2.0.2. I have tried your config json and still could't work,could you please share your  actual config? thank you very much!

**Comment by shaomai00** [comment]
I have solved this problem by using: with keras 2.0.2
{
"image_data_format": "channels_last",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"
}

**Comment by dooliu** [comment]
I have encountered the valueError Attempeted relative import in non-package at the from .Layer import iLayer

**Comment by lucktroy** [comment]
@dooliu could you pls open a new issue and print the detailed errors?

**Comment by dooliu** [comment]
@lucktroy  yes,the details as follow:
Traceback (most recent call last):
  File "STResNet.py", line 109, in <module>
    model = stresnet(external_dim=28, nb_residual_unit=12)
  File "STResNet.py", line 83, in stresnet
    from .iLayer import iLayer
ValueError: Attempted relative import in non-package

**Comment by bingo619** [comment]
I think it is because you did not do this

To install DeepST, cd to the DeepST folder and run the install command:

python setup.py install
To install the development version:

python setup.py develop

**Comment by dooliu** [comment]
@bingo619  Yes，I have installed the DeepST lfollwed as readme in homepage，and run the STResNet in deepst and dist ,both around the problem.

**Comment by justme36** [comment]
I met this problem,and the full informations as follow.

/usr/bin/python3.5 /home/lpm/桌面/DeepST-master/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py
Using TensorFlow backend.
factor:  1.2570787221094177
loading data...
incomplete days:  []
train_data shape:  (4152, 2, 16, 8)
min: 0.0 max: 267.0
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
train shape: (3480, 6, 16, 8) (3480, 2, 16, 8) test shape:  (240, 6, 16, 8) (240, 2, 16, 8)
Traceback (most recent call last):
  File "/home/lpm/桌面/DeepST-master/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 149, in <module>
    main()
  File "/home/lpm/桌面/DeepST-master/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 79, in main
    preprocess_name='preprocessing.pkl', meta_data=True)
  File "/home/lpm/桌面/DeepST-master/deepst/datasets/BikeNYC.py", line 80, in load_data
    meta_feature = timestamp2vec(timestamps_Y)
  File "/home/lpm/桌面/DeepST-master/deepst/preprocessing/__init__.py", line 14, in timestamp2vec
    vec = [time.strptime(t[:8], '%Y%m%d').tm_wday for t in timestamps]  # python2
  File "/home/lpm/桌面/DeepST-master/deepst/preprocessing/__init__.py", line 14, in <listcomp>
    vec = [time.strptime(t[:8], '%Y%m%d').tm_wday for t in timestamps]  # python2
  File "/usr/lib/python3.5/_strptime.py", line 504, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.5/_strptime.py", line 310, in _strptime
    raise TypeError(msg.format(index, type(arg)))
TypeError: strptime() argument 0 must be str, not <class 'bytes'>

Process finished with exit code 1
Can you help me to solve this problem?

**Comment by bingo619** [comment]
@justme36 Try not to use python 3.5

**Comment by justme36** [comment]
@bingo619  thank you ,and I have another problem.

/usr/bin/python2.7 /home/lpm/PycharmProjects/untitled1/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/lpm/PycharmProjects/untitled1/scripts/papers/AAAI17/BikeNYC/exptBikeNYC.py", line 12, in <module>
    from keras.optimizers import Adam
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 6, in <module>
    from .engine import Layer
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 24, in <module>
    from .. import callbacks as cbks
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 26, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
ImportError: No module named tensorboard.plugins

**Comment by vincent-inspectionapps** [comment]
What is your keras and tensorflow version?

**Comment by justme36** [comment]
keras 2.0.5 tensorflow 2.7

**Comment by vincent-inspectionapps** [comment]
Definitely try tensorflow 1.0

**Comment by justme36** [comment]
Thank for your help,I solved it.  @vincent-inspectionapps

**Comment by justme36** [comment]
How can use this model to predict the inflow/outflow？Can you help me?

**Comment by ranairasheed** [comment]
Hi Dear I am trying to run this given code and I am facing the following error:
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e5bb8ab49f8e> in <module>()
     74 
     75 if __name__ == '__main__':
---> 76     main()

<ipython-input-2-e5bb8ab49f8e> in main()
     12     print(
     13         "**at the first time, it takes a few minites to compile if you use [Theano] as the backend**")
---> 14     model = build_model(external_dim)
     15     hyperparams_name = 'c{}.p{}.t{}.resunit{}.lr{}'.format(
     16         len_closeness, len_period, len_trend, nb_residual_unit, lr)

<ipython-input-1-8f060efc1d55> in build_model(external_dim)
     62 
     63     model = stresnet(c_conf=c_conf, p_conf=p_conf, t_conf=t_conf,
---> 64                      external_dim=external_dim, nb_residual_unit=nb_residual_unit)
     65     adam = Adam(lr=lr)
     66     model.compile(loss='mse', optimizer=adam, metrics=[metrics.rmse])

~\Desktop\New folder\DeepST-master\DeepST-master\deepst\models\STResNet.py in stresnet(c_conf, p_conf, t_conf, external_dim, nb_residual_unit)
     70             # [nb_residual_unit] Residual Units
     71             residual_output = ResUnits(_residual_unit, nb_filter=64,
---> 72                               repetations=nb_residual_unit)(conv1)
     73             # Conv2
     74             activation = Activation('relu')(residual_output)

~\Desktop\New folder\DeepST-master\DeepST-master\deepst\models\STResNet.py in f(input)
     43             init_subsample = (1, 1)
     44             input = residual_unit(nb_filter=nb_filter,
---> 45                                   init_subsample=init_subsample)(input)
     46         return input
     47     return f

~\Desktop\New folder\DeepST-master\DeepST-master\deepst\models\STResNet.py in f(input)
     34         residual = _bn_relu_conv(nb_filter, 3, 3)(input)
     35         residual = _bn_relu_conv(nb_filter, 3, 3)(residual)
---> 36         return _shortcut(input, residual)
     37     return f
     38 

~\Desktop\New folder\DeepST-master\DeepST-master\deepst\models\STResNet.py in _shortcut(input, residual)
     18 
     19 def _shortcut(input, residual):
---> 20     return merge([input, residual], mode='sum')
     21 
     22 

TypeError: 'module' object is not callable

Can anyone guide me? Thanks

**Comment by Leerw** [comment]
My environment: python3.7.1, tensorflow1.13.0, keras2.2.4
1. modify keras.json
```
{
"image_data_format": "channels_last",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"
}
```
to
```
{
"image_data_format": "channels_first",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"
}
```
2.  use `add` rather than `merge`
in STResNet.py modify as follows:
```
# from keras.layers import merge
from keras.layers import add
# merge([input, residual], mode='sum')
add([input, residual])
```
