### ISSUE TITLE
stresnet发现了problem

### ISSUE THREAD

**Issue by jyh764790374** [lucktroy/DeepST#10]
你好，我是太原理工大学的一名本科生，最近我在使用您的代码和模型，但是我发现你的核心代码stresnet.py的代码中的conv2D中缺少参数data_format="channels_first"， 导致程序不能正常运行，同时十分感谢您的程序和模型给予我们团队很大帮助

**Comment by lucktroy** [comment]
Thanks. 这个问题可能在keras版本升级引起的. 我们是在keras 1.2进行测试的. 如果您使用的是keras 2.x, 需要修改~/.keras/keras.json进行设置, 把"image_dim_ordering": "channels_first"
