### ISSUE TITLE
If i want to reload the model, what should i do

### ISSUE THREAD

**Issue by EchoRickZz** [lucktroy/DeepST#11]
When i want to reload the model in another file, it puts up  an error like this: iLayer is not defined.
Actually, i import the iLayer module successfully, and i can create a class named iLayer, but when i want to use load_model, it puts up an error above
![image](https://user-images.githubusercontent.com/20631709/34403335-991bd9fa-ebe2-11e7-8c42-0db6e3ed1a2c.png)
![image](https://user-images.githubusercontent.com/20631709/34403346-a29cf5ea-ebe2-11e7-958f-d015d69d3be3.png)

**Comment by lucktroy** [comment]
It seems a python question, you may ask this question in some webites like stackoverflow. 
We also can help if you can put your code here. Thanks.

**Comment by tttrzpt** [comment]
i meet the same problem,can you solve it now?

**Comment by lucktroy** [comment]
@EchoRickZz @tttrzpt 

@tttrzpt 
You may take a look at https://github.com/keras-team/keras/issues/5956

`iLayer` is a custom layer, you may load model like: 

```
from deepst.models.iLayer import iLayer
model = load_model('saved_model_name.h5', custom_objects={"iLayer": iLayer})
```
