### ISSUE TITLE
Could you please give the predictions code?

### ISSUE THREAD

**Issue by tttrzpt** [lucktroy/DeepST#12]
I'm a postgraduate from UCAS，and be interested in your project.Thank you very much!

**Comment by lucktroy** [comment]
you may load the model, and use [keras](https://keras.io) function `model.predict` for predicting.

**Comment by tttrzpt** [comment]
when i load the trained model,i meet the problem as follow:
![image](https://user-images.githubusercontent.com/12119736/34926659-e2fbe8aa-f9eb-11e7-8a8e-5f1f6dd167e5.png)

model=load_model('D:\DeepST-master\DeepST-master\scripts\papers\AAAI17\TaxiBJ\MODEL\\test_best.h5')

**Comment by lucktroy** [comment]
@tttrzpt 
You may take a look at https://github.com/keras-team/keras/issues/5956

`iLayer` is a custom layer, you may load model like: 

```
from deepst.models.iLayer import iLayer
model = load_model('saved_model_name.h5', custom_objects={"iLayer": iLayer})
```

**Comment by tttrzpt** [comment]
That's OK !t=Thank you very much!
