### ISSUE TITLE
关于 X_train and Y_train存在几个问题

### ISSUE THREAD

**Issue by tttrzpt** [lucktroy/DeepST#13]
1.X_train是否可以看作归一化的训练样本，Y_train看作标签？
2.如果1成立那么为什么Y_train打印出来是一堆-1到-0.8的浮点数，Y_train是怎么定义的？
3.要做预测，model.predict()方法中的参数需要重新构造吗？也就是需要对原数据进行重组吗？
劳烦大牛在百忙之中解答，在此万分感谢！！！

**Comment by lucktroy** [comment]
1. X_train, Y_train都来自原始的时间序列, 我们是在原始时间序列上做简单的归一化的
2. 可以看下Y_train的最大值和最小值，应该是-1和1
3. predict的时候需要的X的格式跟X_train必须一致

**Comment by LMdeLiangMi** [comment]
# minmax_scale
    data_train = np.vstack(copy(data_all))[:-len_test]
    print('train_data shape: ', data_train.shape)
    mmn = MinMaxNormalization()
    mmn.fit(data_train)
    data_all_mmn = [mmn.transform(d) for d in data_all]

fit到的min跟max是训练数据里面的，但是后面transform了所有数据，会不会出现测试数据不在[-1, 1]的情况。x_test > max
       x_test = (x_test - min) / (max - min).
       x_test = x_test * 2 - 1

**Comment by LMdeLiangMi** [comment]
XC_train, XP_train, XT_train, Y_train = XC[
        :-len_test], XP[:-len_test], XT[:-len_test], Y[:-len_test]
    XC_test, XP_test, XT_test, Y_test = XC[
        -len_test:], XP[-len_test:], XT[-len_test:], Y[-len_test:]
    timestamp_train, timestamp_test = timestamps_Y[
        :-len_test], timestamps_Y[-len_test:]

    X_train = []
    X_test = []
    for l, X_ in zip([len_closeness, len_period, len_trend], [XC_train, XP_train, XT_train]):
        if l > 0:
            X_train.append(X_)
    for l, X_ in zip([len_closeness, len_period, len_trend], [XC_test, XP_test, XT_test]):
        if l > 0:
            X_test.append(X_)
    print('train shape:', XC_train.shape, Y_train.shape,
          'test shape: ', XC_test.shape, Y_test.shape)

    if metadata_dim is not None:
        meta_feature_train, meta_feature_test = meta_feature[
            :-len_test], meta_feature[-len_test:]
        X_train.append(meta_feature_train)
        X_test.append(meta_feature_test)
    for _X in X_train:
        print(_X.shape, )
    print()
    for _X in X_test:
        print(_X.shape, )
    print()

请问可以在划分完测试集和训练集之后再归一化吗？感觉data_train和X_test在内容上可能有重叠？

**Comment by tttrzpt** [comment]
X_test我打印到文件看过，没有出现超过[-1,1]的数据。。。
我遇到的问题是:
在做预测的时候，X_test本身就是一堆归一化的参数，所以预测的结果也是一堆（-1,1）的参数，这样就达不到预测人流量的效果了。。。
所以我用原始数据集合自己构造x_test，然而总是报格式不对的错误。。。。就很愁，研二狗指望这个项目毕业。。。
DATAPATH = Config().DATAPATH
data_all = []
timestamps_all = list()
len_closeness =3
len_period = 1
len_trend = 1
for year in range(16, 17):
    fname = os.path.join(
        DATAPATH, 'TaxiBJ', 'BJ{}_M32x32_T30_InOut.h5'.format(year))
    # print("file name: ", fname)
    stat(fname)
    data, timestamps = load_stdata(fname)
    # print(timestamps)
    data[data < 0] = 0
    data1 = data[0]
    data2=data[1]
    data3=data[2]
    print(np.shape(data1))
    data_all.append(data1)
    data_all.append(data2)
    data_all.append(data3)
    timestamps_all.append(timestamps)
    print(data_all)
    print(np.shape(data_all))
    print(timestamps_all)
    print(np.shape(timestamps_all))
x_test=[]
for l, X_ in zip([len_closeness, len_period, len_trend], [data]):
        if l >0:
            x_test.append(X_)

model=load_model("D:\DeepST-master\DeepST-master\scripts\papers\AAAI17\TaxiBJ\MODEL\c3.p1.t1.resunit12.lr0.0002.noExternal.best.h5",
                 custom_objects={"iLayer":iLayer,"rmse":rmse})
print("start predict")
predictions=model.predict(x_test,batch_size=32,verbose=0)
for i in predictions:
    print(i,"\n")
print(len(predictions))

**Comment by LMdeLiangMi** [comment]
如果知道x_test, min, max……解个方程得x_test0？
x_test = (x_test0 - min) / (max - min)
x_test = x_test * 2 - 1
