### ISSUE TITLE
how long does it takes to  train the DeepST modal

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [lucktroy/DeepST#2]
how long does it takes to  train the DeepST modal ?
one or two hours?   seven or eight hours ?  or  several days?

**Comment by lucktroy** [comment]
Hi, @cloud-waiting-for-wind the running time depends on many factors, like GPU card and cudnn versions, the configuration of neural networks (i.e., the lengths of the _closeness_, _period_, _trend_ dependents, the depth of network, ...).  In our experiment, it costs about 250sec/epoch on TaxiBJ. The configuration:

the length of the _closeness_: 3
the length of the _period_: 1
the length of the _trend_ : 1
the number of residual units: 4
BN or not: Yes
GPU card: Tesla K40m

Thanks.
