### ISSUE TITLE
would you mind to share your LSTM contrast experiment code ?

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [lucktroy/DeepST#3]
would you mind to  share your LSTM contrast experiment code?
 it didn't tell  the details in the paper.

**Comment by lucktroy** [comment]
@cloud-waiting-for-wind hi, this directory only contains the code of the methods proposed in our AAAI17 paper. 

In our journal version, we add some experiments using LSTM (https://arxiv.org/abs/1701.02543). At present, the paper is still under review. We will show the more detailed setting in the next version. 

Alternatively, you may try Keras RNN: https://keras.io/layers/recurrent/

Thanks.

**Comment by LMdeLiangMi** [comment]
would you mind to share your contrast experiment code such as HA, ARIMA, SARIMA, VAR, ST-ANN?
