### ISSUE TITLE
Only layers of same output shape can be merged using sum mode.

### ISSUE THREAD

**Issue by liaocs2008** [lucktroy/DeepST#4]
I got following error when reproducing experiment results on TaxiBJ. Should it be concatenated or summing up?

> /deepst/models/STResNet.py", line 87, in stresnet
> ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 32, 2), (None, 2, 32, 2), (None, 2, 32, 2)]

**Comment by lucktroy** [comment]
https://github.com/lucktroy/DeepST/issues/1
