### ISSUE TITLE
How can use this model to predict the inflow/outflow?

### ISSUE THREAD

**Issue by ZhangJing1048** [lucktroy/DeepST#5]
The program just show the process of training the dataset and evaluating the trained model,but i can't find a entry/function to predict the inflow/outflow and output them?Could help me with this problem?
Thank very much! @lucktroy

**Comment by ZhangJing1048** [comment]
Actually I want to know how can i see the result of predict dircectly?

**Comment by ZhangJing1048** [comment]
I try to use a function:
predict = model.predict(X_test,batch_size=X_test.shape[0], verbose=0)
to return the result,and the description of predict said that the return should be a Numpy array of predictions,but actually it returns a list.
and the predict() need a para of data(such as X_test),i mus input a history data to predict the futhre data.
I want to know how can i predict the inflow/outflow of tomorrow if i just the data(inflow/outflow) of the past

**Comment by lucktroy** [comment]
One method is predicting inflow/outflow step by step. In detail, predict inflow/outflow at time T+1, which is further as an input for predicting inflow/outflow at time T+2, ....
Then you can get the inflow/outflow at time T+N. 
You may see Algorithm 2 in our extended version: https://arxiv.org/pdf/1701.02543.pdf

**Comment by justme36** [comment]
Hello,did you solve the problem?I have encountered this problem, can you tell me? @ZhangJing1048

**Comment by qingjiu** [comment]
So,did you solve the problem? Can you tell me ?   @ZhangJing1048 @justme36

**Comment by lucktroy** [comment]
@qingjiu Would you pls create a new issue and describe the problem in detail? Thanks
