### ISSUE TITLE
Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 32, 2), (None, 2, 32, 2), (None, 2, 32, 2)]

### ISSUE THREAD

**Issue by shaomai00** [lucktroy/DeepST#6]
I got an error : 
 File "/home/wmx/transfer/workspace/DeepST/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ-L12.py", line 137, in main
    model = build_model(external_dim)
  File "/home/wmx/transfer/workspace/DeepST/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ-L12.py", line 64, in build_model
    external_dim=external_dim, nb_residual_unit=nb_residual_unit)
  File "/home/wmx/anaconda2/envs/tensorflow/lib/python2.7/site-packages/DeepST-0.0.1-py2.7.egg/deepst/models/STResNet.py", line 88, in stresnet
    main_output = merge(new_outputs, mode='sum')

ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 32, 2), (None, 2, 32, 2), (None, 2, 32, 2)]

I 'm using Theano backend. How should I fix this problem?

**Comment by shaomai00** [comment]
and here is my keras configuration json:
{
    "epsilon": 1e-07,
    "floatx": "float32",
    "image_dim_ordering":"th",
    "backend": "theano"
}

thank you very much~!

**Comment by shaomai00** [comment]
my keras version is 2.0.2
and I also tried this config:
{
"image_data_format": "channels_last",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"
}
still have this error T^T
Neither of tensorflow or theano  can work

**Comment by shaomai00** [comment]
I have solved this problem by using: with keras 2.0.2
{
"image_data_format": "channels_first",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "theano"
}

**Comment by lucktroy** [comment]
@shaomai00 thanks!

**Comment by xingkongyidian** [comment]
@shaomai00  hello , I am using keras 2.2.0 ,theano as backend , and my  keras configuration json is
{
"image_data_format": "channels_first",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "theano"
}.  I have replaced the merge([xx, xx], mode='sum') function with add() function. However I met the error like this Operands could not be broadcast together with shapes (6, 32, 2) (2, 32, 32), have you ever met the problem

**Comment by ZhichaoDuan** [comment]
> @shaomai00 hello , I am using keras 2.2.0 ,theano as backend , and my keras configuration json is
> {
> "image_data_format": "channels_first",
> "epsilon": 1e-07,
> "floatx": "float32",
> "backend": "theano"
> }. I have replaced the merge([xx, xx], mode='sum') function with add() function. However I met the error like this Operands could not be broadcast together with shapes (6, 32, 2) (2, 32, 32), have you ever met the problem

Did you solved this problem? Cause I met the same trouble.

**Comment by KingWang93** [comment]
me too! anyone solved this problem?

**Comment by KingWang93** [comment]
> > @shaomai00 hello , I am using keras 2.2.0 ,theano as backend , and my keras configuration json is
> > {
> > "image_data_format": "channels_first",
> > "epsilon": 1e-07,
> > "floatx": "float32",
> > "backend": "theano"
> > }. I have replaced the merge([xx, xx], mode='sum') function with add() function. However I met the error like this Operands could not be broadcast together with shapes (6, 32, 2) (2, 32, 32), have you ever met the problem
> 
> Did you solved this problem? Cause I met the same trouble.

did you solve this problem?
keras 2.2
python 3.6.4

**Comment by Leerw** [comment]
My environment: python3.7.1, tensorflow1.13.0, keras2.2.4
1. modify keras.json
```
{
"image_data_format": "channels_last",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"
}
```
to
```
{
"image_data_format": "channels_first",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"
}
```
2.  use `add` rather than `merge`
in STResNet.py modify as follows:
```
# from keras.layers import merge
from keras.layers import add
# merge([input, residual], mode='sum')
add([input, residual])
```
