### ISSUE TITLE
error about running on tensorflow

### ISSUE THREAD

**Issue by gaoxuesong** [lucktroy/DeepST#7]
Hi,
Please help me to fix the bug.
I am running BikeNYC data on Tensorflow 1.1 and Anaconda3-4.2.0 (Python 3.5).
I have change timestamp2vec and pickle to support tensorflow and python3.
my keras.json is like:
{
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow",
    "image_data_format": "channels_last"
}

But it occur error, the debug like this.  How to fix it?
***********************************************************************************************
(tensorflow) C:\deepst\scripts\papers\AAAI17\BikeNYC>python exptBikeNYC.py
Using TensorFlow backend.
factor:  1.2570787221094177
loading data...
incomplete days:  []
train_data shape:  (4152, 2, 16, 8)
min: 0.0 max: 267.0
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
XC shape:  (3720, 6, 16, 8) XP shape:  (3720, 8, 16, 8) XT shape:  (3720, 8, 16, 8) Y shape: (3720, 2, 16, 8)
train shape: (3480, 6, 16, 8) (3480, 2, 16, 8) test shape:  (240, 6, 16, 8) (240, 2, 16, 8)
(3480, 6, 16, 8)
(3480, 8, 16, 8)
(3480, 8, 16, 8)
(3480, 8)

(240, 6, 16, 8)
(240, 8, 16, 8)
(240, 8, 16, 8)
(240, 8)

 days (test):  [b'20140921', b'20140922', b'20140923', b'20140924', b'20140925', b'20140926', b'20140927', b'20140928', b'20140929', b'20140930']
==========
compiling model...
**at the first time, it takes a few minites to compile if you use [Theano] as the backend**
C:\Anaconda3\lib\site-packages\deepst-0.0.1-py3.5.egg\deepst\models\STResNet.py:69: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), padding="same", filters=64)`
  nb_filter=64, nb_row=3, nb_col=3, border_mode="same")(input)
C:\Anaconda3\lib\site-packages\deepst-0.0.1-py3.5.egg\deepst\models\STResNet.py:28: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), padding="same", filters=64, strides=(1, 1))`
  return Convolution2D(nb_filter=nb_filter, nb_row=nb_row, nb_col=nb_col, subsample=subsample, border_mode="same")(activation)
C:\Anaconda3\lib\site-packages\deepst-0.0.1-py3.5.egg\deepst\models\STResNet.py:20: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return merge([input, residual], mode='sum')
C:\Anaconda3\lib\site-packages\keras\legacy\layers.py:460: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
C:\Anaconda3\lib\site-packages\deepst-0.0.1-py3.5.egg\deepst\models\STResNet.py:76: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), padding="same", filters=2)`
  nb_filter=nb_flow, nb_row=3, nb_col=3, border_mode="same")(activation)
C:\Anaconda3\lib\site-packages\keras\engine\topology.py:604: UserWarning: Class `deepst.models.iLayer.iLayer` defines `get_output_shape_for` but does not override `compute_output_shape`. If this is a Keras 1 layer, please implement `compute_output_shape` to support Keras 2.
  output_shape = self.compute_output_shape(input_shape)
C:\Anaconda3\lib\site-packages\deepst-0.0.1-py3.5.egg\deepst\models\STResNet.py:87: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  main_output = merge(new_outputs, mode='sum')
Traceback (most recent call last):
  File "exptBikeNYC.py", line 152, in <module>
    main()
  File "exptBikeNYC.py", line 90, in main
    model = build_model(external_dim)
  File "exptBikeNYC.py", line 68, in build_model
    external_dim=external_dim, nb_residual_unit=nb_residual_unit)
  File "C:\Anaconda3\lib\site-packages\deepst-0.0.1-py3.5.egg\deepst\models\STResNet.py", line 87, in stresnet
    main_output = merge(new_outputs, mode='sum')
  File "C:\Anaconda3\lib\site-packages\keras\legacy\layers.py", line 460, in merge
    name=name)
  File "C:\Anaconda3\lib\site-packages\keras\legacy\layers.py", line 111, in __init__
    node_indices, tensor_indices)
  File "C:\Anaconda3\lib\site-packages\keras\legacy\layers.py", line 155, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 16, 2), (None, 8, 16, 2), (None, 8, 16, 2)]

**Comment by lucktroy** [comment]
https://github.com/lucktroy/DeepST/issues/1

**Comment by gaoxuesong** [comment]
The follow config doesn't work.

Tensorflow 1.1 and Anaconda3-4.2.0 (Python 3.5).
keras.json is like:
{
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow",
"image_data_format": "channels_last"
}

**Comment by lucktroy** [comment]
@gaoxuesong , our data format shoube "channels_first", please try again. BTW, we have not tested under python 3.5.
