### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by CodingMicheloni** [lucktroy/DeepST#9]
The datasets are not in the onedrive anymore.
Where can we find it? 

Thanks a lot

**Comment by lucktroy** [comment]
@CodingMicheloni it seems there is a broken link in OneDrive, we will fix it ASAP. Alternatively, you can download the data from BaiduYun. 
TaxiBJ: http://pan.baidu.com/s/1qYq7ja8#list/path=%2F
BikeNYC: http://pan.baidu.com/s/1mhIPrRE#list/path=%2F

**Comment by lucktroy** [comment]
@CodingMicheloni we have fixed the links of OneDrive. Please try again. Thanks for submitting the issue.

**Comment by CodingMicheloni** [comment]
Thank you very much for the fast reply. I was now able to download the data from Baidu. OneDrive is not working.
